CREATE DATABASE IF NOT EXISTS aiqdatabase;
USE aiqdatabase;

CREATE TABLE IF NOT EXISTS POSTS (
    POST_ID BIGINT UNSIGNED NOT NULL COMMENT '投稿ID',
    INFLUENCER_ID INT UNSIGNED NOT NULL COMMENT 'インフルエンサーID',
    SHORTCODE VARCHAR(255) COMMENT 'ショートコード',
    LIKES INT UNSIGNED DEFAULT 0 COMMENT 'いいね数',
    COMMENTS INT UNSIGNED DEFAULT 0 COMMENT 'コメント数',
    THUMBNAIL VARCHAR(4096) COMMENT 'サムネイル',
    BODY TEXT COMMENT '本文',
    POST_DATE DATETIME COMMENT '登校日',
    PRIMARY KEY(POST_ID)
) COMMENT='インスタグラム投稿データ';
